// angular-todo/src/components/todo-item/todo-item.component.ts
import { Component, Input, Output, EventEmitter } from '@angular/core';

@Component({
  selector: 'app-todo-item',
  templateUrl: './todo-item.component.html',
  styleUrls: ['./todo-item.component.css']
})
export class TodoItem {

  @Input() public todo: any;
  @Output() public checkmarkChange = new EventEmitter<any>()

  public onCheckboxChange(): void {
    this.checkmarkChange.emit({
      id: this.todo.id,
      value: !this.todo.checked
    })
  }
}

<div class="todo-item-container" [ngClass]="{'todo-item-completed': todo.checked}">
  <input class="todo-item-checkbox" type="checkbox" (change)="onCheckboxChange()" [checked]="todo.checked"/>
  <div class="todo-item-text">
    {{todo.text}}
  </div>
</div>

// react-todo/src/components/TodoItem.tsx
import React from 'react';
import './TodoItem.css';
import classNames from "classnames";

// @ts-ignore
function TodoItem({todo, onCheckboxChange}) {

  function checkboxChange() {
    onCheckboxChange({
      id: todo.id,
      value: !todo.checked
    })
  }

  console.log(todo);

  return (
    <div className={classNames('todo-item-container', {'todo-item-completed': todo.checked})}>
      <input className="todo-item-checkbox" type="checkbox" onChange={checkboxChange} checked={todo.checked}/>
      <div className="todo-item-text">
        {todo.text}
      </div>
    </div>
  );
}

export default TodoItem;
