// angular-todo/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  public todos: any[] = [];
  public inputValue = '';

  public createTodo(): void {
    if (this.inputValue) {
      this.todos = [
        ...this.todos,
        {
          id: this.todos.length,
          text: this.inputValue,
          checked: false,
        }
      ];

      this.inputValue = '';
    }
  }

  public checkTodo(event: any): void {
    this.todos = this.todos.map(todo => {
      if (todo.id === event.id) {
        return {
          ...todo,
          checked: event.value
        };
      }

      return todo;
    })
  }
}

<app-layout>
  <div class="create-todo-container">
    <label for="todo-input">Todo:</label>
    <input type="text" id="todo-input" placeholder="New todo ..." [(ngModel)]="inputValue" >
    <button (click)="createTodo()">Create</button>
  </div>

  <div class="todos-container">
    <app-todo-item *ngFor="let todo of todos" [todo]="todo" (checkmarkChange)="checkTodo($event)"></app-todo-item>
  </div>
</app-layout>

// vue-todo/src/App.vue
<script setup lang="ts">
import {ref} from 'vue'
import Layout from './components/Layout.vue'
import TodoItem from '@/components/TodoItem.vue'

let inputValue = ref<string | undefined>('');
const todos = ref<any[]>([]);

function createTodo () {
  if (inputValue) {
    todos.value = [
      ...todos.value,
      {
        id: todos.value.length,
        text: inputValue.value,
        checked: false
      }
    ]

    inputValue.value = undefined;
  }
}

function checkTodo (event: any) {
  todos.value = todos.value.map(todo => {
    if (todo.id === event.detail.id) {
      return {
        ...todo,
        checked: event.detail.value
      }
    }

    return todo
  })
}
</script>

<template>
  <Layout>
    <div class="create-todo-container">
      <label for="todo-input">Todo:</label>
      <input type="text" id="todo-input" placeholder="New todo ..." v-model="inputValue">
      <button v-on:click="createTodo">Create</button>
    </div>

    <div class="todos-container">
      <TodoItem v-for="todo in todos" :key="todo.id" :todo="todo" v-bind:checkmarkChange={checkTodo} />
    </div>
  </Layout>
</template>
